apiVersion: v1
data:
  rsyslog.conf: "#LEON WOZ ERE\n\n# rsyslog configuration file\n\n# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html\n#
    or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html \n# If
    you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html\n\n####
    MODULES ####\n\nmodule(load=\"imuxsock\" \t  # provides support for local system
    logging (e.g. via logger command)\n       SysSock.Use=\"off\") # Turn off message
    reception via local log socket; \n\t\t\t  # local messages are retrieved through
    imjournal now.\nmodule(load=\"imjournal\" \t    # provides access to the systemd
    journal\n       StateFile=\"imjournal.state\") # File to store the position in
    the journal\n#module(load=\"imklog\") # reads kernel messages (the same are read
    from journald)\n#module(load=\"immark\") # provides --MARK-- message capability\n\n#
    Provides UDP syslog reception\n# for parameters see http://www.rsyslog.com/doc/imudp.html\n#module(load=\"imudp\")
    # needs to be done just once\n#input(type=\"imudp\" port=\"514\")\n\n# Provides
    TCP syslog reception\n# for parameters see http://www.rsyslog.com/doc/imtcp.html\n#module(load=\"imtcp\")
    # needs to be done just once\n#input(type=\"imtcp\" port=\"514\")\n\n#### GLOBAL
    DIRECTIVES ####\n\n# Where to place auxiliary files\nglobal(workDirectory=\"/var/lib/rsyslog\")\n\n#
    Use default timestamp format\nmodule(load=\"builtin:omfile\" Template=\"RSYSLOG_TraditionalFileFormat\")\n\n#
    Include all config files in /etc/rsyslog.d/\ninclude(file=\"/etc/rsyslog.d/*.conf\"
    mode=\"optional\")\n\n#### RULES ####\n\n# Log all kernel messages to the console.\n#
    Logging much else clutters up the screen.\n#kern.*                                                 /dev/console\n\n#
    Log anything (except mail) of level info or higher.\n# Don't log private authentication
    messages!\n*.info;mail.none;authpriv.none;cron.none                /var/log/messages\n\n#
    The authpriv file has restricted access.\nauthpriv.*                                              /var/log/secure\n\n#
    Log all the mail messages in one place.\nmail.*                                                  -/var/log/maillog\n\n\n#
    Log cron stuff\ncron.*                                                  /var/log/cron\n\n#
    Everybody gets emergency messages\n*.emerg                                                 :omusrmsg:*\n\n#
    Save news errors of level crit and higher in a special file.\nuucp,news.crit                                          /var/log/spooler\n\n#
    Save boot messages also to boot.log\nlocal7.*                                                /var/log/boot.log\n\n\n#
    ### sample forwarding rule ###\n#action(type=\"omfwd\"  \n# An on-disk queue is
    created for this action. If the remote host is\n# down, messages are spooled to
    disk and sent when it is up again.\n#queue.filename=\"fwdRule1\"       # unique
    name prefix for spool files\n#queue.maxdiskspace=\"1g\"         # 1gb space limit
    (use as much as possible)\n#queue.saveonshutdown=\"on\"       # save messages
    to disk on shutdown\n#queue.type=\"LinkedList\"         # run asynchronously\n#action.resumeRetryCount=\"-1\"
    \   # infinite retries if host is down\n# Remote Logging (we use TCP for reliable
    delivery)\n# remote_host is: name/ip, e.g. 192.168.0.1, port optional e.g. 10514\n#Target=\"remote_host\"
    Port=\"XXX\" Protocol=\"tcp\")\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rsyslog
