apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb
    ports:
    - containerPort: 3306
    env:
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysqlrootcreds
          key: MARIADB_ROOT_PASSWORD
