apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: 
    image: nginx:alpine
    ports:
    - containerPort: 80
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: "password123"
