apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    environment: test
    app: web
  name: webtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      environment: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
        environment: test
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
