apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: webservice
spec:
  ports:
  - name: web
    port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: LoadBalancer
