apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    environment: test
    app: web
  name: webtestservice
spec:
  ports:
  - name: webtestservice
    port: 5001
    protocol: TCP
    targetPort: 80
  selector:
    app: web
    environment: test
  type: LoadBalancer
